### Get all applicants
GET http://localhost:3000/applicants

### Get all jobs
GET http://localhost:3000/jobs

### Get a single applicant
GET http://localhost:3000/applicants/68766fad4b8575abe6537f72    


### Get a single job
GET http://localhost:3000/jobs/68767b8dd9a29c62e40531cf

### Create a new applicant
POST http://localhost:3000/applicants HTTP/1.1
Content-Type: application/json

{
  "name": "Sarah Johnson",
  "email": "test@test.com",
  "resumeLink": "https://drive.google.com/sarah-resume",
}

### Create a new job
POST http://localhost:3000/jobs HTTP/1.1  
Content-Type: application/json

{
  "title": "Frontend Developer",
  "description": "Responsible for building user interfaces.",
  "location": "New York, NY",
}

### PUT applicant  
PUT http://localhost:3000/applicants/68766fad4b8575abe6537f72   HTTP/1.1
Content-Type: application/json

{
 "name": "Marcus Reed",
  "email": "test@test.com",
  "resumeLink": "https://linkedin.com/in/mreed"
}
### PUT job
PUT http://localhost:3000/jobs/68767b8dd9a29c62e40531cf HTTP/1.1
Content-Type: application/json

{
  "title": "Software Engineer",
  "description": "Develop and maintain web applications.",
  "location": "Remote",
}

### Delete a applicant

DELETE http://localhost:3000/applicants/68766fad4b8575abe6537f72
const express = require('express');
const applicantsController = require('../controllers/applicantsController');        

### Delete a job
DELETE http://localhost:3000/jobs/68767b8dd9a29c62e40531cf
const router = express.Router();
const jobController = require('../controllers/jobController');