openapi: 3.0.0
info:
  title: Book & Author API
  description: A simple REST API for managing books and authors
  version: 1.0.0

paths:
  /api/authors: 
    get:
      summary: Get all authors
      responses:
        '200':
          description: A list of authors
    post:
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author created

  /api/books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created

  /api/books/{id}:
    put:
      summary: Update a book
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated
    delete:
      summary: Delete a book
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book deleted

components:
  schemas:
    Author:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bio:
          type: string
        birthdate:
          type: string
          format: date
    Book:
      type: object
      required:
        - title
        - authorId
      properties:
        title:
          type: string
        genre:
          type: string
        publishedYear:
          type: integer
        pages:
          type: integer
        price:
          type: number
        inStock:
          type: boolean
        authorId:
          type: string
